### ISSUE TITLE
Create application doesn't appear for New Login

### ISSUE THREAD

**Issue by srirampotluri** [DataAnalyticsinStudentHands/TerryApplicationApp#45]
When I created new login credentials and enter the application, instead of "create application" it shows "delete application" for around 5-8 seconds and then "create application" button appears.
![screen shot 2015-01-15 at 11 28 48 am](https://cloud.githubusercontent.com/assets/8973449/5762860/1b26c6ec-9cab-11e4-944e-f243a0e667cf.png)

**Comment by srirampotluri** [comment]
Even the same happens when we login after creating the application. It shows "DELETE APPLICATION" instead of showing APPLICATION IN PROGRESS......It takes 5-8 seconds for that to appear.

**Comment by peggylind** [comment]
This is not going to be a problem in the new version of the app, since we changed the business logic.
